language: python

dist: xenial

python:
  - '3.7'

env: TRAVIS=true

install:
  - pip install --upgrade setuptools pip
  - pip install cython
  - pip install -r requirements.txt
  - pip install qgrid
  - pip install nbval
  - pip install git+git://github.com/Leguark/scikit-image@master
  - pip install vtk
  - pip install pyevtk
  - pip install dataclasses emg3d pyvista panel discretize

script:

  - pytest -v notebooks/integrations/ --nbval-lax --ignore-glob='*discret*'
  - pytest -v notebooks/examples/ --nbval-lax --current-env --ignore-glob='*pography*' --ignore-glob='*lesmodel*' --ignore-glob='*Course*'
  - pytest -v notebooks/tutorials/ --nbval-lax --current-env --ignore-glob='*ch1-6*' --ignore-glob='ch1-7*' --ignore-glob='*ch1-10*' --ignore-glob='*MaskedMarchinCube_Onlap_relations*'
  - pytest

cache: pip

